zram-swap: robustify mkswap/swapon/swapoff invocation
Instead of assuming /sbin contains the correct BusyBox symlinks, directly invoke
the busybox executable. The required utilities are guaranteed to be present,
since the zram-swap package selects them. Additionally, don't assume busybox
resides in /bin, rely on PATH to find it.

While at it, update the copyright year, use SPDX and switch to AUTORELEASE.

Signed-off-by: Rui Salvaterra <rsalvaterra@gmail.com>

diff --git a/package/system/zram-swap/files/zram.init b/package/system/zram-swap/files/zram.init
--- a/package/system/zram-swap/files/zram.init
+++ b/package/system/zram-swap/files/zram.init
@@ -2,32 +2,27 @@
 
 START=15
 
-extra_command "compact" "Trigger compaction for all zram swap devices"
-extra_command "status" "Print out information & statistics about zram swap devices"
+extra_command "compact" "Trigger compaction for all Z-RAM swap dev's"
+extra_command "status" "Print out information & statistics about Z-RAM swap devices"
 
-zram_applicable()
+ram_getsize()
 {
-	local zram_dev="$1"
+	local line
 
-	[ -e "$zram_dev" ] || {
-		logger -s -t zram_applicable -p daemon.crit "device '$zram_dev' not found"
-		return 1
-	}
+	while read line; do case "$line" in MemTotal:*) set $line; echo "$2"; break ;; esac; done </proc/meminfo
+}
 
-	[ -x /sbin/mkswap ] || {
-		logger -s -t zram_applicable -p daemon.err "BusyBox 'mkswap' not installed"
-		return 1
-	}
+zram_getsize()	# in megabytes
+{
+	local zram_size="$( uci -q get system.@system[0].zram_size_mb )"
+	local ram_size="$( ram_getsize )"
 
-	[ -x /sbin/swapon ] || {
-		logger -s -t zram_applicable -p daemon.err "BusyBox 'swapon' not installed"
-		return 1
-	}
-
-	[ -x /sbin/swapoff ] || {
-		logger -s -t zram_applicable -p daemon.err "BusyBox 'swapoff' not installed"
-		return 1
-	}
+	if [ -z "$zram_size" ]; then
+		# e.g. 6mb for 16mb-routers or 61mb for 128mb-routers
+		echo $(( ram_size / 2048 ))
+	else
+		echo "$zram_size"
+	fi
 }
 
 zram_dev()
@@ -59,43 +54,22 @@ zram_getdev()
 	echo $zdev
 }
 
-zram_setup_dev()
+zram_comp_algo()
 {
 	local dev="$1"
 	local zram_comp_algo="$( uci -q get system.@system[0].zram_comp_algo )"
-	local zram_exp_ratio="$( uci -q get system.@system[0].zram_comp_ratio )"
-	local zram_ram_percent="$( uci -q get system.@system[0].zram_ram_percentage )"
-	local zram_priority=`cat /proc/swaps | tail -n +2 | awk '{print $5}' | sort | tail -n 1 | { grep . || echo -1; }`
 
 	if [ -z "$zram_comp_algo" ]; then
-		# default to lzo, which is always available
+		# lzo-rle fails on small RAM devices, default to lzo, which is always available
 		zram_comp_algo="lzo"
 	fi
 
-	if [ -z "$zram_exp_ratio" ]; then
-		 # default to a 2:1 compression ratio
-		zram_exp_ratio="2"
-	fi
-
-	if [ -z "$zram_ram_percent" ]; then
-		# default to 10 % of the total RAM
-		zram_ram_percent="10"
-	fi
-
 	if [ $(grep -c "$zram_comp_algo" /sys/block/$( basename $dev )/comp_algorithm) -ne 0 ]; then
-		logger -s -t zram_comp_algo -p daemon.debug "set compression algorithm '$zram_comp_algo' for zram '$dev'"
+		logger -s -t zram_comp_algo -p daemon.debug "Set compression algorithm '$zram_comp_algo' for zram '$dev'"
 		echo $zram_comp_algo > "/sys/block/$( basename $dev )/comp_algorithm"
 	else
-		logger -s -t zram_comp_algo -p daemon.debug "compression algorithm '$zram_comp_algo' is not supported for '$dev'"
+		logger -s -t zram_comp_algo -p daemon.debug "Compression algorithm '$zram_comp_algo' is not supported for '$dev'"
 	fi
-
-	local zram_size=$(awk -v zer="$zram_exp_ratio" -v zrp="$zram_ram_percent" '(/MemTotal:/) {printf("%.0f\n", $2 * 1024 * (zrp / 100) * zer)}' /proc/meminfo)
-
-	echo $zram_size > "/sys/block/$( basename "$dev" )/disksize"
-
-	/sbin/mkswap "$dev"
-	/sbin/swapon -d -p "$(( $zram_priority < 0 ? 0 : $zram_priority+1 ))" "$zram_dev"
-
 }
 
 #print various stats info about zram swap device
@@ -105,7 +79,7 @@ zram_stats()
 
 	printf "\nGathering stats info for zram device \"$( basename "$1" )\"\n\n"
 
-	printf "ZRAM\n-----\n"
+	printf "Z-RAM\n-----\n"
 	printf "%-25s - %s\n" "Block device" $zdev
 	awk '{ printf "%-25s - %d MiB\n", "Device size", $1/1024/1024 }' <$zdev/disksize
 	printf "%-25s - %s\n" "Compression algo" "$(cat $zdev/comp_algorithm)"
@@ -157,13 +131,28 @@ start()
 	}
 
 	if [ $( grep -cs zram /proc/swaps ) -ne 0 ]; then
-		logger -s -t zram_start -p daemon.notice "zram swap is already mounted"
+		logger -s -t zram_start -p daemon.notice "[OK] zram swap is already mounted"
 		return 1
 	fi
 
 	local zram_dev="$( zram_getdev )"
-	zram_applicable "$zram_dev" || return 1
-	zram_setup_dev "$zram_dev"
+
+	[ -e "$zram_dev" ] || {
+		logger -s -t zram_start -p daemon.crit "[ERROR] device '$zram_dev' not found"
+		return 1
+	}
+
+	local zram_size="$( zram_getsize )"
+	local zram_priority="$( uci -q get system.@system[0].zram_priority )"
+	zram_priority=${zram_priority:+-p $zram_priority}
+
+	logger -s -t zram_start -p daemon.debug "activating '$zram_dev' for swapping ($zram_size MegaBytes)"
+
+	zram_reset "$zram_dev" "enforcing defaults"
+	zram_comp_algo "$zram_dev"
+	echo $(( $zram_size * 1024 * 1024 )) >"/sys/block/$( basename "$zram_dev" )/disksize"
+	busybox mkswap "$zram_dev"
+	busybox swapon -d $zram_priority "$zram_dev"
 }
 
 stop()
@@ -172,7 +161,7 @@ stop()
 
 	for zram_dev in $( grep zram /proc/swaps |awk '{print $1}' ); do {
 		logger -s -t zram_stop -p daemon.debug "deactivate swap $zram_dev"
-		/sbin/swapoff "$zram_dev" && zram_reset "$zram_dev" "claiming memory back"
+		busybox swapoff "$zram_dev" && zram_reset "$zram_dev" "claiming memory back"
 		local dev_index="$( echo $zram_dev | grep -o "[0-9]*$" )"
 		if [ $dev_index -ne 0 ]; then
 			logger -s -t zram_stop -p daemon.debug "removing zram $zram_dev"
